hm = {'Rust': ('5% of 21k', 'https://www.linkedin.com/skill-assessments/Rust%20(Programming%20Language)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Python': ('15% of 3.8M', 'https://www.linkedin.com/skill-assessments/Python%20(Programming%20Language)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Machine Learning': ('5% of 1.3M','https://www.linkedin.com/skill-assessments/Machine%20Learning/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Cybersecurity': ('30% of 1.1M','https://www.linkedin.com/skill-assessments/Cybersecurity/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Linux': ('5% of 1.2M','https://www.linkedin.com/skill-assessments/Linux/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Azure': ('15% of 720k','https://www.linkedin.com/skill-assessments/Microsoft%20Azure/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'AWS': ('5% of 1.3M','https://www.linkedin.com/skill-assessments/Amazon%20Web%20Services%20(AWS)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'AWS Lambda': ('15% of 98k','https://www.linkedin.com/skill-assessments/AWS%20Lambda/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'GCP': ('15% of 361k','https://www.linkedin.com/skill-assessments/Google%20Cloud%20Platform%20(GCP)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'REST APIs': ('30% of 586k','https://www.linkedin.com/skill-assessments/REST%20APIs/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'MySQL': ('15% of 1.6M','https://www.linkedin.com/skill-assessments/MySQL/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'NoSQL': ('15% of 147k','https://www.linkedin.com/skill-assessments/NoSQL/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'Hadoop': ('15% of 192','https://www.linkedin.com/skill-assessments/Hadoop/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'MongoDB': ('30% of 179k','https://www.linkedin.com/skill-assessments/MongoDB/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'Git': ('5% of 1.3M','https://www.linkedin.com/skill-assessments/Git/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'C': ('',''),
      'C++': ('',''),
      'Java': ('',''),
      'Android': ('',''),
      'Kotlin': ('',''),
      'XML': ('',''),
      'Swift': ('',''),
      'Objective-C': ('',''),
      'Front-end': ('',''),
      'JavaScript': ('',''),
      'Node': ('',''),
      'React': ('',''),
      'Ruby': ('',''),
      'HTML': ('',''),
      'CSS': ('',''),
      'Django': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      'OOP': ('',''),
      'Agile': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      }