hm = {'Rust': ('5% of 21k',
               "https://www.linkedin.com/skill-assessments/Rust%20(Programming%20Language)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D"),
      'Python': ('15% of 3.8M',
                 "https://www.linkedin.com/skill-assessments/Python%20(Programming%20Language)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D"),
      'Machine Learning': ('5% of 1.3M',
                           "https://www.linkedin.com/skill-assessments/Machine%20Learning/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D"),
      'Cybersecurity': ('30% of 1.1M',
                        "https://www.linkedin.com/skill-assessments/Cybersecurity/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D"),
      'Linux': ('5% of 1.2M',
                "https://www.linkedin.com/skill-assessments/Linux/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D"),
      'Azure': ('15% of 720k',
                "https://www.linkedin.com/skill-assessments/Microsoft%20Azure/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D"),
      'AWS': ('5% of 1.3M',
              "https://www.linkedin.com/skill-assessments/Amazon%20Web%20Services%20(AWS)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D"),
      'AWS Lambda': ('15% of 98k',
                     "https://www.linkedin.com/skill-assessments/AWS%20Lambda/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D"),
      'GCP': ('15% of 361k',
              "https://www.linkedin.com/skill-assessments/Google%20Cloud%20Platform%20(GCP)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D"),
      'REST APIs': ('30% of 586k','https://www.linkedin.com/skill-assessments/REST%20APIs/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'MySQL': ('15% of 1.6M','https://www.linkedin.com/skill-assessments/MySQL/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'NoSQL': ('15% of 147k','https://www.linkedin.com/skill-assessments/NoSQL/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'Hadoop': ('15% of 192','https://www.linkedin.com/skill-assessments/Hadoop/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'MongoDB': ('30% of 179k','https://www.linkedin.com/skill-assessments/MongoDB/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'Git': ('5% of 1.3M','https://www.linkedin.com/skill-assessments/Git/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BHc9RRbFARaK3tiaHmyfFrA%3D%3D'),
      'C': ('15% of 1.6M','https://www.linkedin.com/skill-assessments/C%20(Programming%20Language)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'C++': ('5% of 1.4M','https://www.linkedin.com/skill-assessments/C++/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Java': ('5% of 2.8M','https://www.linkedin.com/skill-assessments/Java/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Android': ('30% of 980k','https://www.linkedin.com/skill-assessments/Android/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Kotlin': ('15% of 122k','https://www.linkedin.com/skill-assessments/Kotlin/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'XML': ('5% of 238k','https://www.linkedin.com/skill-assessments/XML/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Swift': ('5% of 199k','https://www.linkedin.com/skill-assessments/Swift%20(Programming%20Language)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Objective-C': ('5% of 84k','https://www.linkedin.com/skill-assessments/Objective-C/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Front-end': ('5% of 873k',
                    "https://www.linkedin.com/skill-assessments/Front-end%20Development/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D"),
      'JavaScript': ('5% of 2.2M','https://www.linkedin.com/skill-assessments/JavaScript/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Node': ('5% of 392k','https://www.linkedin.com/skill-assessments/Node.js/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'React': ('5% of 797k','https://www.linkedin.com/skill-assessments/Node.js/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Ruby': ('5% of 76k','https://www.linkedin.com/skill-assessments/Ruby%20on%20Rails/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'HTML': ('5% of 3.3M','https://www.linkedin.com/skill-assessments/HTML/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'CSS': ('5% of 1.7M','https://www.linkedin.com/skill-assessments/Cascading%20Style%20Sheets%20(CSS)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Django': ('5% of 156k','https://www.linkedin.com/skill-assessments/Django/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'OOP': ('5% of 1.1M','https://www.linkedin.com/skill-assessments/Object-Oriented%20Programming%20(OOP)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'Agile': ('5% of 3.0M','https://www.linkedin.com/skill-assessments/Agile%20Methodologies/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BhD%2BMvwl5R0e5JnEW122HQA%3D%3D'),
      'IT Operations': ('30% of 1.4M','https://www.linkedin.com/skill-assessments/IT%20Operations/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BgRQEtQtLS9iwZruXA8z4Tg%3D%3D'),
      '.NET Framework': ('5% of 823k','https://www.linkedin.com/skill-assessments/.NET%20Framework/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BgRQEtQtLS9iwZruXA8z4Tg%3D%3D'),
      'Bash': ('5% of 330k','https://www.linkedin.com/skill-assessments/Bash/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BgRQEtQtLS9iwZruXA8z4Tg%3D%3D'),
      'Go': ('5% of 66k','https://www.linkedin.com/skill-assessments/Go%20(Programming%20Language)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BgRQEtQtLS9iwZruXA8z4Tg%3D%3D')
      }