hm = {'Rust': ('5% of 21k', 'https://www.linkedin.com/skill-assessments/Rust%20(Programming%20Language)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Python': ('15% of 3.8M', 'https://www.linkedin.com/skill-assessments/Python%20(Programming%20Language)/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Machine Learning': ('5% of 1.3M','https://www.linkedin.com/skill-assessments/Machine%20Learning/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Cybersecurity': ('30% of 1.1M','https://www.linkedin.com/skill-assessments/Cybersecurity/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Linux': ('5% of 1.2M','https://www.linkedin.com/skill-assessments/Linux/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      'Azure': ('15% of 720k','https://www.linkedin.com/skill-assessments/Microsoft%20Azure/report/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_skills_details%3BSpnvGKfZSPeFPBbPOkUWiA%3D%3D'),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      'Android': ('',''),
      'Kotlin': ('',''),
      'OOP': ('',''),
      'Front-end': ('',''),
      'Agile': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      '': ('',''),
      }